# Generated by Django 5.2.11 on 2026-03-09 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_display_name', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/images/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='profiles/covers/')),
                ('bio', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('non_binary', 'Non-binary'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20)),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bust_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('waist_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hips_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('shoe_size', models.CharField(blank=True, max_length=10)),
                ('hair_color', models.CharField(blank=True, max_length=50)),
                ('eye_color', models.CharField(blank=True, max_length=50)),
                ('instagram_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('available_for_editorial', models.BooleanField(default=False)),
                ('available_for_runway', models.BooleanField(default=False)),
                ('available_for_commercial', models.BooleanField(default=False)),
                ('available_for_fittings', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('is_discoverable', models.BooleanField(default=False)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending'), ('verified', 'Verified')], default='unverified', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('represented_by_agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='represented_models', to='agencies.agency')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='model_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Model Profile',
                'ordering': ['-created_at'],
            },
        ),
    ]
