# Generated by Django 5.2.11 on 2026-03-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelprofile',
            name='inseam_cm',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
