# Generated by Django 5.2.11 on 2026-03-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0002_modelprofile_inseam_cm'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
