# Generated by Django 5.2.12 on 2026-03-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0003_modelprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelprofile',
            name='custom_agency_name',
            field=models.CharField(blank=True, help_text='Agency name when the agency is not on the platform.', max_length=255),
        ),
        migrations.AlterField(
            model_name='modelprofile',
            name='bust_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='modelprofile',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='modelprofile',
            name='hips_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='modelprofile',
            name='inseam_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='modelprofile',
            name='waist_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
