# Generated by Django 6.0.3 on 2026-03-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0004_modelprofile_custom_agency_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelprofile',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('amateur', 'Amateur'), ('experienced', 'Experienced')], max_length=20),
        ),
    ]
