# Generated by Django 6.0.3 on 2026-03-19 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0005_modelprofile_experience_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelprofile',
            name='experience_level',
        ),
    ]
