# Generated by Django 6.0.3 on 2026-03-21 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0006_remove_modelprofile_experience_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelprofile',
            name='is_discoverable',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='modelprofile',
            name='is_public',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
