# Generated by Django 5.2.11 on 2026-03-09 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='agencies/logos/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='agencies/covers/')),
                ('short_tagline', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('headquarters_address', models.CharField(blank=True, max_length=255)),
                ('website_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('founded_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('featured_order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending'), ('verified', 'Verified')], default='unverified', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_accepting_applications', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agencies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Agencies',
                'ordering': ['featured_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AgencyHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('related_model_name', models.CharField(blank=True, max_length=255)),
                ('related_brand_name', models.CharField(blank=True, max_length=255)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='agencies/highlights/')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='agencies.agency')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='AgencyRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('menswear', 'Menswear'), ('womenswear', 'Womenswear'), ('all', 'All'), ('editorial', 'Editorial'), ('commercial', 'Commercial'), ('runway', 'Runway')], default='all', max_length=20)),
                ('min_height_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_height_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('age_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('age_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('accepts_beginners', models.BooleanField(default=False)),
                ('application_guidance_text', models.TextField(blank=True)),
                ('active_from', models.DateField(blank=True, null=True)),
                ('active_to', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='agencies.agency')),
            ],
            options={
                'ordering': ['-is_current', 'category'],
            },
        ),
        migrations.CreateModel(
            name='AgencyStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(blank=True, max_length=100)),
                ('can_review_applications', models.BooleanField(default=True)),
                ('can_edit_agency', models.BooleanField(default=False)),
                ('is_primary_contact', models.BooleanField(default=False)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='agencies.agency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_staff_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Agency Staff',
                'unique_together': {('user', 'agency')},
            },
        ),
    ]
