# Generated by Django 5.2.12 on 2026-03-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_agency_is_roster_public_agencyban'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='is_requirements_public',
            field=models.BooleanField(default=True),
        ),
    ]
