# Generated by Django 5.2.12 on 2026-03-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0003_agency_is_requirements_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyrequirement',
            name='category',
            field=models.CharField(choices=[('all', 'All'), ('editorial_male', 'Editorial (Male)'), ('editorial_female', 'Editorial (Female)'), ('runway_male', 'Runway (Male)'), ('runway_female', 'Runway (Female)'), ('commercial_male', 'Commercial (Male)'), ('commercial_female', 'Commercial (Female)')], default='all', max_length=20),
        ),
    ]
