# Generated by Django 5.2.12 on 2026-03-12 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0005_agencyrequirement_measurements_colors'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyPortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='agencies/portfolio/')),
                ('caption', models.TextField(blank=True)),
                ('credit', models.CharField(blank=True, help_text='e.g. Photographer, brand, or campaign name', max_length=255)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='agencies.agency')),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
