# Generated by Django 6.0.3 on 2026-03-19 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0008_agencyrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencyrequest',
            name='message',
        ),
        migrations.AddField(
            model_name='agencyrequest',
            name='about_agency',
            field=models.TextField(blank=True, help_text='Tell us about your agency'),
        ),
        migrations.AddField(
            model_name='agencyrequest',
            name='agency_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='agencyrequest',
            name='agency_instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='agencyrequest',
            name='agency_website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='agencyrequest',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='agencyrequest',
            name='role_at_agency',
            field=models.CharField(blank=True, help_text='e.g. Owner, Booker, Manager', max_length=100),
        ),
    ]
