# Generated by Django 6.0.3 on 2026-03-19 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0009_remove_agencyrequest_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
