# Generated by Django 6.0.3 on 2026-03-19 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0010_alter_agencyrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyrequest',
            name='created_agency',
            field=models.OneToOneField(blank=True, help_text='Auto-created when status is set to Accepted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_request', to='agencies.agency'),
        ),
    ]
