# Generated by Django 5.2.12 on 2026-03-19 16:46

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0011_agencyrequest_created_agency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencyrequirement',
            name='accepts_beginners',
        ),
    ]
