# Generated by Django 5.2.12 on 2026-03-21 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0012_remove_agencyrequirement_accepts_beginners'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agencyportfoliopost',
            unique_together={('agency', 'slug')},
        ),
    ]
