# Generated by Django 5.2.11 on 2026-03-09 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
        ('models_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('contacted', 'Contacted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20)),
                ('cover_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='agencies.agency')),
                ('agency_requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='agencies.agencyrequirement')),
                ('applicant_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='models_app.modelprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('applicant_profile', 'agency')},
            },
        ),
        migrations.CreateModel(
            name='ApplicationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bust_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('waist_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hips_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('portfolio_summary', models.TextField(blank=True)),
                ('selected_portfolio_posts', models.JSONField(blank=True, default=list)),
                ('submission_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot', to='applications.application')),
            ],
        ),
    ]
