# Generated by Django 5.2.11 on 2026-03-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsnapshot',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='applicationsnapshot',
            name='inseam_cm',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
