# Generated by Django 5.2.11 on 2026-03-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_applicationsnapshot_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='feedback_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
