# Generated by Django 6.0.3 on 2026-03-21 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0007_alter_modelprofile_is_discoverable_and_more'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='portfoliopost',
            unique_together={('owner_profile', 'slug')},
        ),
    ]
